### 🟡 Crear un nuevo usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Santiago",
  "lastName": "zuñiga",
  "email": "ziñiga5@gmail.com",
  "password": "abc156",
  "Id_rol": 6

}


### 🟢 Obtener todos los usuarios
GET http://localhost:3000/users

### 🟢 Obtener un usuario por ID
GET http://localhost:3000/users/7

### 🔵 Actualizar un usuario existente
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "firstName": "Ana",
  "lastName": "Gómez",
  "email": "ana@example.com",
  "password": "123456",
  "Id_rol": 8
}

### 🔴 Eliminar un usuario existente
DELETE http://localhost:3000/users/7

