# Crear detalle de factura
POST http://localhost:3000/detabill
Content-Type: application/json
{
  "Id_bill": 2,
  "Id_product_service": 1,
  "price": 50000,
  "quantity": 2
}

# Obtener todos
GET http://localhost:3000/detabill

# Actualizar
PATCH http://localhost:3000/detabill/1
Content-Type: application/json
{
  "quantity": 3
}

# Eliminar
DELETE http://localhost:3000/detabill/1
