PUT http://localhost:3000/usuario/1
Content-Type: application/json

{
    "nombre": "Juan Gomez",
    "edad": 30,
    "email": "juan@example.com"
}

PUT http://localhost:3000/usuario
Content-Type: application/json

{
    "nombre": "Ana Perez",
    "edad": 28,
    "email": "ana@example.com"
}

DELETE http://localhost:3000/usuario/1

DELETE http://localhost:3000/usuario
Content-Type: application/json

{
    "ids": [2, 3, 4]
}
