### 1. Listar todas las plataformas
GET http://localhost:3000/plataformas

### 2. Ver juegos de una plataforma (ID=1)
GET http://localhost:3000/plataformas/1/juegos

### 3. Eliminar una plataforma (ID=1)
DELETE http://localhost:3000/plataformas/1

### 4. Eliminar un juego (ID=1) de una plataforma (ID=1)
DELETE http://localhost:3000/plataformas/1/juegos/1
