POST http://localhost:3000/medical-staff
Content-Type: application/json

//tener en cuenta que a lo hora de poner el número de telefono este debe existir en la vida real
{
    "identification": "1096803380",
    "phone": "+573214076917", 
    "Id_specialty":8,
    "Id_users": 8
}

GET http://localhost:3000/medical-staff

//actualización por medio de id

PATCH http://localhost:3000/medical-staff/1096803380
Content-Type: application/json
{
    "phone": "+573204069122",
    "Id_speciality": 4
}

DELETE http://localhost:3000/medical-staff/7





