POST http://localhost:3000/medical-history
Content-Type: application/json
{
    "hist_date": "2024/10/25",
    "hist_time": "14:30",
    "hist_diagnosys": "Cáncer de páncreas",
    "hist_treatment": "Tratamiento con Oncología",
    "Id_appo": 9, 
    "Id_pet": 3,
    "Id_users": [8, 6] 
}


GET http://localhost:3000/medical-history


// Reemplaza {id} con el ID primario del historial (ej: 1)
GET http://localhost:3000/medical-history/6


PATCH http://localhost:3000/medical-history/6
Content-Type: application/json

{
    "hist_diagnosys": "Cáncer de páncreas (Revisado)",
    "Id_users": [8, 6] 
}


DELETE http://localhost:3000/medical-history/1