//Crear
POST http://localhost:3000/produc-service
Content-Type: application/json
{
    "prod_name": "Cita medica",
    "prod_price": 140000,
    "prod_type": "SERVICIO"
}

//MOstrar servicios y productos registrados
GET http://localhost:3000/produc-service

//Cambiar el de servicio a producto o viceverza
PATCH http://localhost:3000/produc-service/1
Content-Type: application/json
{
    "prod_type": "PRODUCTO"
}

//eliminar
DELETE http://localhost:3000/produc-service/5
