
GET http://localhost:3000/client-owners/1

###🟡 Crear una nueva  factura
POST http://localhost:3000/bill
Content-Type: application/json
{
  "Id_client": 1,
  "fac_date": "2025-10-26",
  "fac_total": 50000
}


### 🟢 Obtener todas las facturas
GET http://localhost:3000/bill

### 🟢 Obtener una factura por  id 
GET http://localhost:3000/bill/1

### 🔵 Actualizar una factura existente
PATCH  http://localhost:3000/bill/1
Content-Type: application/json
{
  "fac_total": 150000
}


### 🔴 Eliminar un cliente existente
DELETE http://localhost:3000/bill/1

