### 🟡 Crear un nuevo personal administrativo
POST http://localhost:3000/administrative-staff
Content-Type: application/json

{
  "userId": 2,
  "identification": "1092855563",
  "phone": "3001234457",
  "startDate": "2025-10-15"
}
### 🟢 Obtener todo el personal administrativo
GET http://localhost:3000/administrative-staff  


### 🟢 Obtener un personal administrativo por ID
GET http://localhost:3000/administrative-staff/1

### 🔵 Actualizar un personal administrativo existente
PUT http://localhost:3000/administrative-staff/1
Content-Type: application/json

{
  "userId": 2, 
  "identification": "1092847563",
  "phone": "3001234568",
  "startDate": "2025-10-18"
}
### 🔴 Eliminar un personal administrativo existente
DELETE http://localhost:3000/administrative-staff/1

