### 🟡 Crear una nueva cita
POST http://localhost:3000/appointments
Content-Type: application/json
//tener en cuenta la lista de producto_servicio, tabla productservice
//tener en cuenta la lista de mascotas, tabla pet
//tener en cuenta la lista de usuarios, tabla users
{
  "date": "2025-10-20",
  "time": "10:00",
  "reason": "Medicina general",
  "value": 50000,
  "Id_users": 2,
  "Id_pet": 2,
  "Id_product_service": 5,
  "detail_type": "Consulta general"
}
### 🟢 Obtener todas las citas
GET http://localhost:3000/appointments   

### 🟢 Obtener una cita por ID
GET http://localhost:3000/appointments/1 

### 🔵 Actualizar una cita existente
PUT http://localhost:3000/appointments/8
Content-Type: application/json

{
  "detail_type": "Baño antipulgas",
  "status": "REALIZADA"
}

//saber cuantas citas corresponden al  ID DEL USUARIO 
GET http://localhost:3000/appointments?/Id_users=10

### 🔴 Eliminar una cita existente
DELETE http://localhost:3000/appointments/10
